<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SachSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('sach')->insert([
            // Văn học Việt Nam
            [
                'MaSach' => 1,
                'MaLoai' => 1,
                'TenSach' => 'Dế Mèn Phiêu Lưu Ký',
                'TenNCC' => 'Nhà xuất bản Kim Đồng',
                'Slug' => 'de-men-phieu-luu-ky',
                'TenTG' => 'Tô Hoài',
                'TenBoSach' => null,
                'NXB' => 1941,
                'ISBN' => '123456789',
                'AnhDaiDien' => 'demen.jpg',
                'MoTa' => 'Một câu chuyện phiêu lưu thú vị của chú Dế Mèn.',
                'GiaNhap' => 100000,
                'GiaBan' => 120000,
                'KhuyenMai' => 10,
                'SoLuongTon' => 50,
                'TrangThai' => 1, // Còn hàng
            ],
            [
                'MaSach' => 2,
                'MaLoai' => 1,
                'TenSach' => 'Tắt Đèn',
                'TenNCC' => 'Nhà xuất bản Kim Đồng',
                'Slug' => 'tat-den',
                'TenTG' => 'Ngô Tất Tố',
                'TenBoSach' => null,
                'NXB' => 1939,
                'ISBN' => '223456789',
                'AnhDaiDien' => 'tat-den.jpg',
                'MoTa' => 'Tác phẩm kinh điển phản ánh đời sống nông dân Việt Nam.',
                'GiaNhap' => 80000,
                'GiaBan' => 95000,
                'KhuyenMai' => 15,
                'SoLuongTon' => 0,
                'TrangThai' => 0, // Hết hàng
            ],
            // Văn học nước ngoài
            [
                'MaSach' => 3,
                'MaLoai' => 2,
                'TenSach' => 'Chiến Tranh và Hòa Bình',
                'TenNCC' => 'Nhà xuất bản Khoa học',
                'Slug' => 'chien-tranh-va-hoa-binh',
                'TenTG' => 'Lev Tolstoy',
                'TenBoSach' => null,
                'NXB' => 1869,
                'ISBN' => '323456789',
                'AnhDaiDien' => 'chien-tranh-hoa-binh.png',
                'MoTa' => 'Tác phẩm kinh điển về chiến tranh và hòa bình.',
                'GiaNhap' => 150000,
                'GiaBan' => 180000,
                'KhuyenMai' => 20,
                'SoLuongTon' => 30,
                'TrangThai' => 1, // Còn hàng
            ],
            [
                'MaSach' => 4,
                'MaLoai' => 2,
                'TenSach' => 'Những Người Khốn Khổ',
                'TenNCC' => 'Nhà xuất bản Khoa học',
                'Slug' => 'nhung-nguoi-khon-kho',
                'TenTG' => 'Victor Hugo',
                'TenBoSach' => null,
                'NXB' => 1862,
                'ISBN' => '423456789',
                'AnhDaiDien' => 'nhung-nguoi-khon-kho.jpg',
                'MoTa' => 'Cuốn tiểu thuyết bất hủ về cuộc đời Jean Valjean.',
                'GiaNhap' => 120000,
                'GiaBan' => 140000,
                'KhuyenMai' => 15,
                'SoLuongTon' => 0,
                'TrangThai' => 2, // Ngừng bán
            ],
            // Khoa học - Kỹ thuật
            [
                'MaSach' => 5,
                'MaLoai' => 3,
                'TenSach' => 'Thuyết Tương Đối',
                'TenNCC' => 'Nhà xuất bản Khoa học',
                'Slug' => 'thuyet-tuong-doi',
                'TenTG' => 'Albert Einstein',
                'TenBoSach' => null,
                'NXB' => 1905,
                'ISBN' => '523456789',
                'AnhDaiDien' => 'thuyet-tuong-doi.jpg',
                'MoTa' => 'Lý thuyết nổi tiếng của Albert Einstein.',
                'GiaNhap' => 200000,
                'GiaBan' => 250000,
                'KhuyenMai' => 10,
                'SoLuongTon' => 20,
                'TrangThai' => 1, // Còn hàng
            ],
            [
                'MaSach' => 6,
                'MaLoai' => 3,
                'TenSach' => 'Nguồn Gốc Các Loài',
                'TenNCC' => 'Nhà xuất bản Khoa học',
                'Slug' => 'nguon-goc-cac-loai',
                'TenTG' => 'Charles Darwin',
                'TenBoSach' => null,
                'NXB' => 1859,
                'ISBN' => '623456789',
                'AnhDaiDien' => 'nguon-goc-cac-loai.jpg',
                'MoTa' => 'Tác phẩm nền tảng về thuyết tiến hóa.',
                'GiaNhap' => 180000,
                'GiaBan' => 210000,
                'KhuyenMai' => 15,
                'SoLuongTon' => 0,
                'TrangThai' => 2, // Ngừng bán
            ],
            [
                'MaSach' => 7,
                'MaLoai' => 4,
                'TenSach' => 'One Piece - Hành Trình Vĩ Đại',
                'TenNCC' => 'Nhà xuất bản Kim Đồng',
                'Slug' => 'one-piece-hanh-trinh-vi-dai',
                'TenTG' => 'Eiichiro Oda',
                'TenBoSach' => null,
                'NXB' => 1997,
                'ISBN' => '1023456789',
                'AnhDaiDien' => 'one-piece.png',
                'MoTa' => 'Cuộc phiêu lưu của Luffy và băng hải tặc Mũ Rơm.',
                'GiaNhap' => 25000,
                'GiaBan' => 30000,
                'KhuyenMai' => 5,
                'SoLuongTon' => 200,
                'TrangThai' => 1,
            ],
            [
                'MaSach' => 8,
                'MaLoai' => 4,
                'TenSach' => 'Naruto - Chí Khí Ninja',
                'TenNCC' => 'Nhà xuất bản Kim Đồng',
                'Slug' => 'naruto-chi-khi-ninja',
                'TenTG' => 'Masashi Kishimoto',
                'TenBoSach' => null,
                'NXB' => 1999,
                'ISBN' => '1123456789',
                'AnhDaiDien' => 'naruto.png',
                'MoTa' => 'Hành trình trở thành Hokage của Naruto Uzumaki.',
                'GiaNhap' => 27000,
                'GiaBan' => 32000,
                'KhuyenMai' => 10,
                'SoLuongTon' => 150,
                'TrangThai' => 1,
            ],
            [
                'MaSach' => 9,
                'MaLoai' => 4,
                'TenSach' => 'Thám Tử Lừng Danh Conan',
                'TenNCC' => 'Nhà xuất bản Kim Đồng',
                'Slug' => 'tham-tu-lung-danh-conan',
                'TenTG' => 'Gosho Aoyama',
                'TenBoSach' => null,
                'NXB' => 1994,
                'ISBN' => '1223456789',
                'AnhDaiDien' => 'conan.png',
                'MoTa' => 'Những vụ án bí ẩn được Conan giải mã.',
                'GiaNhap' => 30000,
                'GiaBan' => 35000,
                'KhuyenMai' => 15,
                'SoLuongTon' => 180,
                'TrangThai' => 1,
            ],
            [
                'MaSach' => 10,
                'MaLoai' => 1,
                'TenSach' => 'Con Chó Nhỏ Mang Giỏ Hoa Hồng',
                'TenNCC' => 'Nhà xuất bản Hội Nhà văn',
                'Slug' => 'con-cho-nho-mang-gio-hoa-hong',
                'TenTG' => 'Nguyễn Nhật Ánh',
                'TenBoSach' => null,
                'NXB' => 2020,
                'ISBN' => '624567890',
                'AnhDaiDien' => 'con-cho-nho-mang-gio-hoa-hong.png',
                'MoTa' => 'Một cuốn sách đầy hình ảnh và câu chuyện cảm động.',
                'GiaNhap' => 150000,
                'GiaBan' => 180000,
                'KhuyenMai' => 10,
                'SoLuongTon' => 50,
                'TrangThai' => 1, // Đang bán
            ],
            [
                'MaSach' => 11,
                'MaLoai' => 1,
                'TenSach' => 'Nắng Vườn Xưa',
                'TenNCC' => 'Nhà xuất bản Kim Đồng',
                'Slug' => 'nang-vuon-xua',
                'TenTG' => 'Đoàn Minh Phượng',
                'TenBoSach' => null,
                'NXB' => 2018,
                'ISBN' => '625678901',
                'AnhDaiDien' => 'nang-vuon-xua.png',
                'MoTa' => 'Một tác phẩm thơ ca nhẹ nhàng và sâu lắng.',
                'GiaNhap' => 120000,
                'GiaBan' => 160000,
                'KhuyenMai' => 15,
                'SoLuongTon' => 30,
                'TrangThai' => 1, // Đang bán
            ],
            [
                'MaSach' => 12,
                'MaLoai' => 3,
                'TenSach' => 'Giấc Mơ Mỹ: Đường Đến Stanford',
                'TenNCC' => 'Nhà xuất bản Trẻ',
                'Slug' => 'giac-mo-my-duong-den-stanford',
                'TenTG' => 'Nguyễn Quốc Khánh',
                'TenBoSach' => null,
                'NXB' => 2021,
                'ISBN' => '626789012',
                'AnhDaiDien' => 'giac-mo-my-duong-den-stanford.png',
                'MoTa' => 'Một câu chuyện truyền cảm hứng về ước mơ và nỗ lực.',
                'GiaNhap' => 130000,
                'GiaBan' => 170000,
                'KhuyenMai' => 25,
                'SoLuongTon' => 40,
                'TrangThai' => 1, // Đang bán
            ],
            [
                'MaSach' => 13,
                'MaLoai' => 1,
                'TenSach' => 'Người Thầy',
                'TenNCC' => 'NXB Giáo dục',
                'Slug' => 'nguoi-thay',
                'TenTG' => 'Frank McCourt',
                'TenBoSach' => null,
                'NXB' => 1960,
                'ISBN' => '627890123',
                'AnhDaiDien' => 'nguoi-thay.png',
                'MoTa' => 'Một tác phẩm đầy triết lý và nhân văn.',
                'GiaNhap' => 100000,
                'GiaBan' => 140000,
                'KhuyenMai' => 30,
                'SoLuongTon' => 20,
                'TrangThai' => 1, // Đang bán
            ]

        ]);
    }
}